### ISSUE TITLE
psychopy screen doesn't auto-fit screen size in windows

### ISSUE THREAD

**Issue by JohnGriffiths** [JadinTredup/brainflow-notebooks#1]
screenshot example:

![image](https://user-images.githubusercontent.com/397826/85799257-ec4a3c00-b70c-11ea-84d3-35107706c5cd.png)

...run using code:

```python
from eegnb.experiments.visual_n170 import n170
n170.present(duration=10)
```

The issue is that the grey screen doesn't fill the background. Hence you can see some of my chrome browser in the background

**Comment by JadinTredup** [comment]
Hey John, I just pushed a fix for this. Let me know if this works for you now.
