### ISSUE TITLE
csv file not saved properly at session's end

### ISSUE THREAD

**Issue by basty72** [JadinTredup/brainflow-notebooks#2]
Hi Jadin, I tried the notebook and I was able to get the cyton board streaming to UART, however I have noticed the data is not saved properly at the end of the session from within Jupyter. I attach the error log here and a suggestion for improvement at the end
Cheers
Cris

**_setup:_**
-cloned the notebooks from Jadin (latest update pulled to my local repo: yesterday)
-connected cyton board and got the USB port number
-changed instruction 3 in N170 notebook to:
n170_exp.initialize_eeg(board_type='cyton',usb_port='/dev/cu.usbserial-DM00DS6T')

-ran succesfully N170 from the beginning until instruction 4:

subject_name = 'jadin_test'
duration = 10
trial_num = 3
n170_exp.run_trial(duration=duration,
                   subject=subject_name,
                   run=trial_num)

**_error log :_**
Beginning EEG Stream; Wait 5 seconds for signal to settle... 

---------------------------------------------------------------------------
BrainFlowError                            Traceback (most recent call last)
<ipython-input-4-0d532f6128ef> in <module>
      2 duration = 10
      3 trial_num = 3
----> 4 n170_exp.run_trial(duration=duration,
      5                    subject=subject_name,
      6                    run=trial_num)

~/git/brainflow-notebooks/experiments.py in run_trial(self, duration, subject, run)
    239         data = self.board.get_board_data()
    240         data_fn, event_fn = get_fns(subject, run, self.erp)
--> 241         DataFilter.write_file(data, data_fn, 'w')
    242         self.mywin.close()
    243         self.trials.to_csv(event_fn)

/opt/anaconda3/envs/bfnotebooks/lib/python3.8/site-packages/brainflow/data_filter.py in write_file(cls, data, file_name, file_mode)
    515         res = DataHandlerDLL.get_instance ().write_file (data_flatten, data.shape[0], data.shape[1], file, mode)
    516         if res != BrainflowExitCodes.STATUS_OK.value:
--> 517             raise BrainFlowError ('unable to write file', res)
    518 
    519     @classmethod

BrainFlowError: GENERAL_ERROR:17 unable to write file

**_change suggestion_**

```
 def get_fns(subject, run, paradigm):
    data_fn = os.path.join('data', f'{subject}_{paradigm}_{run}.csv')
    event_fn = os.path.join('data', f'{subject}_{paradigm}_{run}_EVENTS.csv')
```
 

becomes

```
 def get_fns(subject, run, paradigm):
    home = os.getenv("HOME")
    if not os.path.isdir(os.path.join(home,'data')):
        os.makedirs(os.path.join(home,'data'))
    data_fn = os.path.join(home,'data', f'{subject}_{paradigm}_{run}.csv')
    event_fn = os.path.join(home,'data', f'{subject}_{paradigm}_{run}_EVENTS.csv')
    return data_fn, event_fn
```

**Comment by JadinTredup** [comment]
Hey Cris, we are actually working on a new branch which we will eventually push to replace this branch. It is located at [OpenBCI-NTX](https://github.com/JadinTredup/brainflow-notebooks/tree/OpenBCI-NTX). Would you mind checking that one to see if it fixes this issue? I am trying not to mess with the main branch too much until the other is ready to be pushed to master, but if you still want to use the master branch let me know and I will implement a fix today or tomorrow.

**Comment by basty72** [comment]
> Hey Cris, we are actually working on a new branch which we will eventually push to replace this branch. It is located at [OpenBCI-NTX](https://github.com/JadinTredup/brainflow-notebooks/tree/OpenBCI-NTX). Would you mind checking that one to see if it fixes this issue? I am trying not to mess with the main branch too much until the other is ready to be pushed to master, but if you still want to use the master branch let me know and I will implement a fix today or tomorrow.

Hi Jadin,
I tried the new code and works well (correct screen size and succesful save operation). I have only one word of caution regarding the function _stop_brainflow in eeg.py: if for some reason the user inputs a wrong path to the save file the instruction   data_df.to_csv(self.save_fn) (line 140) will fail and the user will see a static gray screen.
I would introduce the following code around line 140:
```
try:
    data_df.to_csv(self.save_fn)
except:
    print("A problem occurred when saving the csv file on disk")
```

**Comment by basty72** [comment]
An even better solution would be to check the path before the experiment starts, so that the user doesn't lose all the data in case the path is misspelled.
Example amendment to n170.py, line 23:

```
if eeg: eeg.start(fn=save_fn)
```
becomes:

```
if eeg:
   #parse save_fn and check if folder exists
   path = os.path.dirname(save_fn)
   fn = os.path.basename(save_fn)
   isFolder = os.path.isfile(path) 
   isFile = os.path.isfile(fn) 
   if isFolder:
      if isFile:
         res = input(f"file {fn} already exists, do you want to overwrite it? (y/n)")
          ...
   else:
        print(f"folder {path} does not exist, please check the path name")
        return
    ....

```

**Comment by JohnGriffiths** [comment]
yes fo sho, the more helpful error checking and reporting the better

**Comment by JadinTredup** [comment]
What do you guys think about checking the path and if it does not exist, it creates a default filename like "UNNAMED_0.csv" and still runs the experiment/saves the data. It could output a message indicating the path it was saved to.

**Comment by JadinTredup** [comment]
I just pushed a fix for this which creates a save file for a "unnamed" subject if none is passed. Let me know if I can close this.
